name: sdk rc
on:
  issue_comment:
    types: [created]
jobs:
  sdk-rc:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/sdk') }}
    env:
      LATEST_COMMENT: ${{ github.event.comment.body }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "$LATEST_COMMENT"
    permissions: write-all
